### PR TITLE
reworked project structure

### PR DESCRIPTION
**Pull request by Icekey**
- Tesseract output gets captured directly instead of parsing it from a file
- added TSV output

### CODE REVIEW

**Comment by thomasgruebl** [comment]
Hi, 

thanks for reworking the project structure!

I'm getting the following errors when I run it:

`
error[E0658]: use of unstable library feature 'command_access'
  --> src/tesseract/command.rs:76:10
   |
76 |         .get_args()
   |          ^^^^^^^^
   |
   = note: see issue #44434 <https://github.com/rust-lang/rust/issues/44434> for more information

error[E0658]: use of unstable library feature 'command_access'
  --> src/tesseract/command.rs:83:17
   |
83 |         command.get_program().to_str().unwrap(),
   |                 ^^^^^^^^^^^
   |
   = note: see issue #44434 <https://github.com/rust-lang/rust/issues/44434> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `rusty-tesseract` due to 2 previous errors
`

**Comment by Icekey** [comment]
Are you using an old rust version? The function "get_args" is stable since 1.57.0.  I always use the newest version of rust so i did not notice. What version should the libary target?

**Comment by thomasgruebl** [comment]
Oh yeah, thanks, might be my current version. I'll update and review the PR asap.

**Comment by Icekey** [comment]
Thank you for merging. If you have suggestions please let me know. I am pretty much done with the rework. Only thing i feel that could be better is the error messaging and documentation of the crate with a https://docs.rs/ site like https://docs.rs/image/0.24.6/image/.

**Pull request merged**
